server:
  port: 8081

spring:
  application:
    name: Catalog Application
  main:
    banner-mode: "off"
  profiles:
    active:  default
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/catalog_app
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver